# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NativeDowloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.TextField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, null=True)),
                ('high', models.TextField(blank=True, null=True)),
                ('audiodownload', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'native_dowloads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedTalks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=245, null=True)),
                ('speaker', models.CharField(blank=True, max_length=245, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=345, null=True)),
            ],
            options={
                'db_table': 'related_talks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=245, null=True)),
                ('is_published', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=85, null=True)),
                ('lastname', models.CharField(blank=True, max_length=85, null=True)),
                ('middleinitial', models.CharField(blank=True, max_length=245, null=True)),
                ('title', models.CharField(blank=True, max_length=245, null=True)),
                ('description', models.CharField(blank=True, max_length=245, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('whatotherssay', models.TextField(blank=True, null=True)),
                ('whotheyare', models.TextField(blank=True, null=True)),
                ('whylisten', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speakers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtitledDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
                ('low', models.TextField(blank=True, null=True)),
                ('high', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subtitled_downloads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalkLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagename', models.CharField(blank=True, db_column='languageName', max_length=45, null=True)),
                ('endonym', models.CharField(blank=True, max_length=45, null=True)),
                ('languagecode', models.CharField(blank=True, db_column='languageCode', max_length=45, null=True)),
                ('ianacode', models.CharField(blank=True, db_column='ianaCode', max_length=45, null=True)),
            ],
            options={
                'db_table': 'talk_languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_id', models.IntegerField(blank=True, null=True)),
                ('threadid', models.CharField(blank=True, max_length=45, null=True)),
                ('num_comments', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=345, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=245, null=True)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('slug', models.CharField(blank=True, max_length=455, null=True)),
                ('institute_partner_name', models.CharField(blank=True, max_length=125, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('salon_partner_name', models.CharField(blank=True, max_length=45, null=True)),
                ('event_badge', models.CharField(blank=True, max_length=45, null=True)),
                ('is_featured', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=345, null=True)),
                ('hero', models.TextField(blank=True, null=True)),
                ('hero_load', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('video_type', models.CharField(blank=True, max_length=145, null=True)),
                ('viewed_count', models.CharField(blank=True, max_length=45, null=True)),
                ('curator_approved', models.IntegerField(blank=True, null=True)),
                ('url_talk', models.TextField(blank=True, null=True)),
                ('row_inserted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalksHasLanguages',
            fields=[
                ('talks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ted.Talks')),
                ('isrtl', models.IntegerField(blank=True, db_column='isRtl', null=True)),
            ],
            options={
                'db_table': 'talks_has_languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalksHasRatings',
            fields=[
                ('talks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ted.Talks')),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talks_has_ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalksHasSpeakers',
            fields=[
                ('talks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ted.Talks')),
            ],
            options={
                'db_table': 'talks_has_speakers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalksHasTags',
            fields=[
                ('talks', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ted.Talks')),
            ],
            options={
                'db_table': 'talks_has_tags',
                'managed': False,
            },
        ),
    ]
