# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentialskey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('acronym', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'credentialskey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=245, null=True)),
                ('offer', models.CharField(blank=True, max_length=145, null=True)),
                ('link', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'moocs',
                'managed': False,
            },
        ),
    ]
